### PR TITLE
Regression tests

### LINKED ISSUE #114: Regression tests as Unit tests
I've been working on getting the regressions tests in [embed](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/README) working as [unit tests](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/test/java/orca/controllers/xmlrpc/OrcaRegressionTest.java), and most of them seem to be [working well](https://github.com/RENCI-NRIG/orca5/tree/regression_tests) enough now, but there a couple of issues.

1. Several of the tests were failing in unit tests with errors like `ERROR: 2:Path does NOT exist` when trying to setup Inter-Domain links (e.g. [TS3-3](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS3/TS3-3.rdf)).  I was able to fix this by copying the substrate files from my emulation environment into the git source code (e.g. [ben-6509.rdf](https://github.com/RENCI-NRIG/orca5/blob/370e44e321a550b132316cf87b5ae3788a25f3c3/ndl/src/main/resources/orca/ndl/substrate/ben-6509.rdf)), but looking back, I don't think this was the right way to fix this (that's why it's in a branch! :)
   - Where should I be looking to get substrate files that work together?  Should I look at functional AM(s)?
1. Some of the tests still are not working in Unit Tests:
   - [TS5-1](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS5/TS5-1.rdf) gives `ERROR: 2:Path does NOT exist` in the unit test.  In emulation, it works fine; but all nodes are placed at a single site.  In live tests, all nodes are again placed at a single site, but the ticketing fails because the image is not found.  I could probably fix the missing image problem, but I'm not sure exactly what this should be testing -- multiple sites? Should this unit test be able to pass?
   - [TS7-1](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS7/TS7-1.rdf) gives the `ERROR: 2:Path does NOT exist` in both the unit test and in emulation.  I'm not sure about how to create stitchports in the live system.  Should this unit test be able to pass?
1. [TS3-13](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS3/TS3-13.rdf) and [TS3-14](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS3/TS3-14.rdf) both seem to work fine in the Unit test, but they fail in emulation with the `ERROR: 4:No Edge Domain Exist`.  So they probably shouldn't be passing in the unit tests?

### PR DESCRIPTION
**Pull request by hinchliff**
There are only a couple of minor changes to production code.

Fixes #114

### CODE REVIEW

**Comment by hinchliff** [comment]
Someone, anyone, please review and merge?  :)

**Comment by ibaldin** [comment]
I will on Monday.

**Comment by YufengXin** [comment]
This looks fine to me. Please go ahead to merge.
Thanks

**Comment by YufengXin** [comment]
This looks fine to me. Please go ahead to merge. Thanks

**Pull request merged**
