### PR TITLE
Fix handler files for 8700 switch

### PR DESCRIPTION
**Pull request by mcevik0**
Handler files that were formatted by the commits below cause errors on switch configuration. These files are modified (reverted).  
- code formatted using formatter-maven-plugin        db21e1cee68e9bdaa5897e1bf578c4fa9918ce62
- more? code formatted using formatter-maven-plugin  0ff070ee9df1293f74b9f16e26f2b33f0f38a71e

### CODE REVIEW

**Comment by ibaldin** [comment]
Do we know if the QFX handler was similarly affected? I believe it uses the same type of XML files.

**Comment by mcevik0** [comment]
It's most likely that QFX handler is affected, too. I will check the files.

**Comment by mcevik0** [comment]
I submitted a new commit to revert all XML files that are affected from formatting. (RENCI-NRIG/orca5@df64d9b1). These files belong to the handlers below:
```
handlers/network:
|-- dtn/InfineraDTN
|-- os/polatis
|-- router/ciena/8700
|-- router/cisco/3400
|-- router/cisco/6509
```

ibm/g8264,  junos/ex3200 and junos/qfx3500 are not affected.

**Comment by mcevik0** [comment]
This branch is deployed to Ciena Hanover rack for testing. Ciena-8700 handler is working fine.

**Pull request merged**
