### PR TITLE
Upgrade to Java 8

### LINKED ISSUE #140: Upgrade to Java 8
Orca needs to _at least_ be able to run using Java 8, even if still compiled by Java 7.  But  it would be preferable to upgrade the source/compilation to Java 8 as well.

Or maybe even Java 9?

Right now, at least in [Docker emulation](https://github.com/RENCI-NRIG/orca5/tree/docker_java_8), Orca will not run using Java 8.

It seems to compile fine using Java 8.   But either way, compiled as 7 or compile as 8 it seems to not run using Java 8.

We need to determine if we can get this running under Java 8, and what may be required to upgrade more fully to Java 8.   It's possible the old Axis libraries will be problematic in any upgrade.

These are the error messages I see when I try to run using Java 8
> 2017-06-15 13:10:48,208-[WrapperSimpleAppMain]-{WARN }-orca-(RemoteRegistryCache.java:510)-singleQueryProcess(): Registry returned a known local actor, skipping

@YufengXin was seeing a different error (please comment if incorrect)
> INFO   | jvm 1    | 2017/06/20 20:04:16 | 2017-06-20 20:04:16,685 [qtp1778861335-36] WARN  org.eclipse.jetty.util.log-(Slf4jLog.java:40) - javax.net.ssl.SSLHandshakeException: General SSLEngine problem

### PR DESCRIPTION
**Pull request by hinchliff**
Fixes #140 

Uses Java 8 for both compilation and runtime.

### CODE REVIEW

**Comment by YufengXin** [comment]
1. when I used "docker-run.sh", the configure files can not be found, not obvious to me as the volumes seem defined right.
2. then I run the three containers manually, and ran into another exception in sm and controller
due to missed jolokia-access.xml.
---------------------------------
2017-08-01 15:53:33,795 [WrapperSimpleAppMain] WARN  /-(ContextHandler.java:2050) - JolokiaServlet: Error while accessing access restrictor at file:///etc/orca/controller-11080/config/jolokia-access.xml. Denying all access to MBeans for security reasons. Exception: java.io.FileNotFoundException: /etc/orca/controller-11080/config/jolokia-access.xml (No such file or directory)
jvm 1    | java.io.FileNotFoundException: /etc/orca/controller-11080/config/jolokia-access.xml (No such file or directory)

**Comment by hinchliff** [comment]
@YufengXin I did change the path for the config files, because I was afraid that many of the would end up being incompatible between Java 7 and 8.  The path now includes the Java version, like `orca-oracle_1.8/`

Turns out that probably wasn't necessary, and we could probably change it back to the older path if necessary.

The Jolokia exception is expected.  That's been present for a while (with Java 7), if you don't add in the configuration file necessary for some of the remote monitoring stuff.   You can safely ignore this exception.

**Comment by mcevik0** [comment]
jolokia-access.xml file can be added to the config directory as below:

```
$ cat << EOF > /etc/orca/controller-11080/config/jolokia-access.xml 
<?xml version="1.0" encoding="UTF-8"?>

<restrict>
   <remote>
     <host>127.0.0.1</host>
     <host>152.54.1.65</host>
    </remote> 
</restrict>
EOF
```

**Comment by YufengXin** [comment]
now the controller cannot talk to sm probably due to this exception found in the controller.log:

-------------------------------
2017-08-01 18:09:17,716 [qtp412927128-104] WARN  org.eclipse.jetty.io.nio-(SelectChannelEndPoint.java:720) - javax.net.ssl.SSLHandshakeException: General SSLEngine problem

**Comment by hinchliff** [comment]
@YufengXin did you have any luck using the config files I sent you?

**Comment by YufengXin** [comment]
The issue turns out to be my BEN user cert that broke the communication between Flukes and the controller. Using my GENI cert works.  merging the pull

**Pull request merged**
