### PR TITLE
146 network element equals

### LINKED ISSUE #146: NetworkElement should correctly implement equals()
I noticed this while working on #137.

The `equals()` for NetworkElement was [previously removed](ttps://github.com/RENCI-NRIG/orca5/commit/e43e81c81ebbed0bfdcd81a5b3e74aac45c8a4ad).

I thought this was going to be an easier fix, but it wasn't too bad.  Nodes can now edited in place, and extra nodes don't need to be deleted at the end of the process.

### PR DESCRIPTION
**Pull request by hinchliff**
I rebased the commits for this issue, to push all of the new tests into the first commit.This way, we are sure that we know the correct behavior of all of the tests that were added.

@YufengXin I will need your help to determine if I added enough test cases to cover the reason why NetworkElement.equals() was [previously removed](https://github.com/RENCI-NRIG/orca5/commit/e43e81c81ebbed0bfdcd81a5b3e74aac45c8a4ad)

Special attention should be made in the review of this pull request to _how_ and/or _if_ ORCA is maintaining interface property numbering through modify requests.  Additional tests may be needed here.  @vjorlikowski may know if NEUCA is dependent upon specific, unmodified, `eth` property naming.

As a separate issue, @vjorlikowski noticed that network interfaces that should have been removed in a Modify request, are not being fully removed.  Some of the tests in this pull request highlight that the removed interfaces are still present in the "local properties".  No attempt has been made to fix this specific issue yet, just to document the current behavior.

Fixes #146

### CODE REVIEW

**Comment by hinchliff** [comment]
[OrcaXmlrpcHandlerTest.java](https://github.com/RENCI-NRIG/orca5/pull/151/files#diff-7b0cb0d6b1ae228a621125c5e0003daa) has gotten messy in this branch.  I would appreciate opinions on the "better" way to produce request/modify files for testing purposes.  Manually create request files, e.g. using Flukes; or generate request files using NDL?

**Comment by ibaldin** [comment]
Ahab

**Comment by hinchliff** [comment]
I definitely looked at Ahab, but it might not be right for what i'm trying to do in these "unit tests"
1. Ahab doesn't provide a mechanism to directly call the createSlice() or modifySlice() methods in OrcaXmlrpcHandler, nor should it.
1. Ahab doesn't _seem_ to provide a mechanism to easily generate the create/modify request RDF that needs to be passed to createSlice() and modifySlice().  The [Slice](https://github.com/RENCI-NRIG/ahab/blob/master/libndl/src/main/java/org/renci/ahab/libndl/Slice.java) class in Ahab can generate these request RDF, but it needs all of the other information to connect to a Controller too.

But maybe I should have been looking at the [SliceGraph](https://github.com/RENCI-NRIG/ahab/blob/master/libndl/src/main/java/org/renci/ahab/libndl/SliceGraph.java) class?

**Comment by hinchliff** [comment]
I don't think Ahab's SliceGraph is going to make test slice creation any easier either, and it uses Ahab's NDLModel, which is mostly just a wrapper for the NdlGenerator that I am currently using in the tests.

I think the pull request is ready now.  Any comments / review?

**Comment by YufengXin** [comment]
go ahead, thanks!

**Pull request merged**
