### PR TITLE
Controller resources 88

### LINKED ISSUE #88: Resource Exhaustion Behavior
This ticket is being split off from #36.  The old ticket should be used to track intra-domain bandwidth exhaustion behavior, while this ticket should be used specifically for the behavior noticed by Anirban and Paul, where [accounting of XL VMs is in error](https://github.com/RENCI-NRIG/orca5/issues/36#issuecomment-256460555).

### PR DESCRIPTION
**Pull request by hinchliff**
Fixes #88.

I think this is a good chance to try-out the idea of doing 'formal' code reviews.  I've been doing a little reading, and this is a decent overview: [Effective Code Reviews – 9 Tips from a Converted Skeptic](https://blog.fogcreek.com/effective-code-reviews-9-tips-from-a-converted-skeptic/)

I think a good thing for us to try is to just use the Review feature in the Pull Request.  Ideally at least two people would review and comment on this pull request.  
* Should take about an hour.  Really this pull request is a little big, but I think an hour should still be OK.
* Use a [checklist](https://blog.fogcreek.com/increase-defect-detection-with-our-code-review-checklist-example/).  Here are a couple of highlights:
   * Does the code work? Does it perform its intended function, the logic is correct etc.
   * Is there any redundant or duplicate code?
   * Can any of the code be replaced with library functions?
   * Is any unusual behavior or edge-case handling described?
   * Do tests exist and are they comprehensive? i.e. has at least your agreed on code coverage.

I'm pretty sure you will be able to find something from the checklist that need review :)

If you want a little further reading on Agile code review, this was also a decent short article: [Why code reviews matter (and actually save time!)](https://www.atlassian.com/agile/code-reviews)

### CODE REVIEW

**Comment by hinchliff** [comment]
Just to point out some of the mechanics of code review within the Pull request:

* You do not need to review each commit individually.
* You can click the [Files changed](https://github.com/RENCI-NRIG/orca5/pull/97/files) tab above, to see the current state of all of the files.
   * You can leave a comment on specific lines in the code diff, by clicking the blue plus sign when mousing over the code.
   * You can use the green `Review changes` button to submit your code review.

There is a little more information available in the GitHub help pages: [About pull request reviews](https://help.github.com/articles/about-pull-request-reviews/)

**Comment by ibaldin** [comment]
Do you envision the reviews happening individually behind closed doors or in a meeting?

**Comment by hinchliff** [comment]
I don't think it needs to be done in a meeting, although I'm not opposed to that.

I hope that individual reviews can be comprehensive by following the suggested length of time (please set aside an hour for review), and by using the checklist as a guide (the full length one, from the article).

**Comment by hinchliff** [comment]
I tagged Paul and Yufeng to do the code reviews.   If you're busy with other work, I can assign someone else.

I'll probably schedule a meeting wth everyone for Monday or Tuesday to go over the code review process, and see what people think...

**Comment by paul-ruth** [comment]
Monday is best.  Yufeng and I are in D.C. Tuesday-Thursday.

Paul

On Jan 27, 2017, at 1:43 PM, hinchliff <notifications@github.com<mailto:notifications@github.com>> wrote:


I tagged Paul and Yufeng to do the code reviews. If you're busy with other work, I can assign someone else.

I'll probably schedule a meeting wth everyone for Monday or Tuesday to go over the code review process, and see what people think...

**Comment by ibaldin** [comment]
I think the meeting is a good idea. Let’s see how the process goes. I’ll try to get to it.

**Comment by hinchliff** [comment]
This pull request has been split in two, see #98 and #99.

**Pull request closed without merging**
