### PR TITLE
Br212 - Integration of Orca with Comet

### PR DESCRIPTION
**Pull request by kthare10**
This branch contains changes required to maintain instance metadata in Comet instead of Openstack. The code is controlled by following configuration parameters in AM orca.properties. If configured, Instance metadata is stored in Comet otherwise, stored in Openstack.

 comethost=https://13.59.255.221:8111/,https://18.218.34.48:8111/
 comet.cacert=/etc/orca/am+broker-12080/ssl/DigiCertCA.der
 comet.clientkeystore=/etc/orca/am+broker-12080/ssl/client.jks
 comet.clientkeystorepwd=changeme
 comet.clientcert=/etc/orca/am+broker-12080/ssl/inno-hn_exogeni_net.pem
 comet.clientkey=/etc/orca/am+broker-12080/ssl/inno-hn_exogeni_net.key

If the above properties are configured and any error occurs in saving the property information in Comet, the operation will fail.

Format of the data for each category stored in Comet is defined in the JSON explained in detail in Issue#212.

Areas of code modified:
a) EC2 Handler (ANT)
     - Exception Handling for failure to update meta data
     - Remove Comet Meta Data on VM remove
b) Neuca EC2 Handler Tasks (JAVA)
     - Modified Generate, Add and Remove tasks to update the meta data in comet instead of openstack when comet is enabled
    - Maintain readtoken and comethost information in global metadata still stored in openstack
c) Comet Interface classes (JAVA)
    - Added 2 classes which implement the logic to interface with comet
d) Comet-remove-vm-scope (Python)
   - Implemented Python client for Comet
   - comet-remove-vm-scope script is used to delete the meta data for an instance from comet on removal

### CODE REVIEW

**Comment by ibaldin** [comment]
@kthare10 you mentioned you haven't tested self-signed certs from VM slivers, did I understand that right?

**Comment by kthare10** [comment]
Comet rejects read requests with Self Signed certificates with SSL_Verify_Error. I verified the certificates by establishing successful SSL connection using open_ssl command. I shared this observation with Cong. Cong suggested that Comet be configured to not need certificates for reads. Current implementation does not validate self signed certificates as per default Comet configuration.

server.ssl.client-auth=want

**Comment by ibaldin** [comment]
I think that's right, according to the latest docs, self-signed client certs are optional for read operations https://github.com/RENCI-NRIG/COMET-Accumulo/tree/master/specifications

**Comment by ibaldin** [comment]
I would change the property names to have "comet." prefix, just so its clear what they are for. We have many different keystores we operate on.

**Comment by kthare10** [comment]
This is a Comet parameter present in comet's application.resources file. This is not an ORCA parameter.

**Comment by ibaldin** [comment]
But its under OrcaConfiguration.java ?

**Comment by kthare10** [comment]
No, its not in OrcaConfiguration.java

**Comment by kthare10** [comment]
Incorporated the suggested configuration parameter name change in code

**Comment by kthare10** [comment]
added code for using round robin to send messages to comet head nodes

**Pull request merged**
